# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(382, 427)
        Dialog.setStyleSheet("#frame {    \n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"background-color:white;\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:black;\n"
"padding-bottom:5px;\n"
"padding-left:3px;\n"
"}\n"
"QLabel{\n"
"font: 12pt \"Bahnschrift SemiCondensed\";\n"
"\n"
"}\n"
"\n"
"#btnEdit {\n"
"    background-color: #48ACAC;\n"
"    border-radius:50px;\n"
"    color:white;\n"
"font: 14pt \"Bahnschrift SemiCondensed\";\n"
"\n"
"}\n"
"#btnEdit:hover{\n"
"background-color: #2F958D;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.projectid_label_3 = QtWidgets.QLabel(self.frame_2)
        self.projectid_label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.projectid_label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.projectid_label_3.setStyleSheet("font: 20pt ;")
        self.projectid_label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projectid_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.projectid_label_3.setObjectName("projectid_label_3")
        self.verticalLayout_4.addWidget(self.projectid_label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.projectid_label_2 = QtWidgets.QLabel(self.frame)
        self.projectid_label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.projectid_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projectid_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.projectid_label_2.setObjectName("projectid_label_2")
        self.gridLayout.addWidget(self.projectid_label_2, 1, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(self.frame)
        self.txtPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 1, 1, 1, 1)
        self.projectid_label = QtWidgets.QLabel(self.frame)
        self.projectid_label.setMinimumSize(QtCore.QSize(70, 0))
        self.projectid_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projectid_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.projectid_label.setObjectName("projectid_label")
        self.gridLayout.addWidget(self.projectid_label, 0, 0, 1, 1)
        self.txtUsername = QtWidgets.QLineEdit(self.frame)
        self.txtUsername.setMinimumSize(QtCore.QSize(0, 30))
        self.txtUsername.setObjectName("txtUsername")
        self.gridLayout.addWidget(self.txtUsername, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.isAdminCheckBox = QtWidgets.QCheckBox(self.frame)
        self.isAdminCheckBox.setText("")
        self.isAdminCheckBox.setObjectName("isAdminCheckBox")
        self.gridLayout.addWidget(self.isAdminCheckBox, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnEdit = QtWidgets.QPushButton(self.frame_3)
        self.btnEdit.setMinimumSize(QtCore.QSize(150, 35))
        self.btnEdit.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEdit.setStyleSheet("")
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout_3.addWidget(self.btnEdit)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit User"))
        self.projectid_label_3.setText(_translate("Dialog", "Edit User"))
        self.projectid_label_2.setText(_translate("Dialog", "Password:"))
        self.projectid_label.setText(_translate("Dialog", "Username:"))
        self.label_17.setText(_translate("Dialog", "is Admin:"))
        self.btnEdit.setText(_translate("Dialog", "Edit"))
